Repository PyWorkflowApp/visual-programming, pull requests merged in 2020-05, with the labels that each got.

#83 Updated/new documentation for custom nodes, CLI, tests
  README.md
  docs/cli.md
  docs/custom_nodes.md
  docs/media/custom_node_missing_package.png
  docs/media/pyworkflow_coverage.svg
  docs/tests.md
Labels: documentation

#92 fix: Add missing row to table display by adding extra index
  front-end/src/components/CustomNode/GraphView.js
Labels: bug

#93 Fixes Jest in master
  front-end/__tests__/components/CustomNode/__snapshots__/GraphView.test.js.snap
  front-end/__tests__/components/CustomNode/__snapshots__/NodeConfig.test.js.snap
  front-end/package-lock.json
  front-end/package.json
  front-end/setupTests.js
  front-end/src/components/CustomAction/CustomDeleteItemsAction.js
  front-end/src/components/CustomNode/GraphView.js
  front-end/src/components/VPPort/VPPortModel.js
Labels: enhancement
